import { boolean, date, integer, jsonb, pgTable, primaryKey, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const bills = pgTable('bills', {
  billKey: text('bill_key').primaryKey(),
  biennium: text('biennium').notNull(),
  chamber: text('chamber').notNull(),
  type: text('type').notNull(),
  number: integer('number').notNull(),
  id: text('id').notNull(),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status'),
  statusDate: date('status_date'),
  currentVersionCode: text('current_version_code'),
  legiscanBillId: integer('legiscan_bill_id'),
  changeHash: text('change_hash'),
  sponsors: jsonb('sponsors').notNull().default([]),
  committee: jsonb('committee'),
  history: jsonb('history').notNull().default([]),
  calendar: jsonb('calendar').notNull().default([]),
  sasts: jsonb('sasts').notNull().default([]),
  referrals: jsonb('referrals').notNull().default([]),
  progress: jsonb('progress').notNull().default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const billVersions = pgTable(
  'bill_versions',
  {
    billKey: text('bill_key').notNull(),
    versionCode: text('version_code').notNull(),
    seq: integer('seq').notNull(),
    label: text('label').notNull(),
    shortLabel: text('short_label').notNull(),
    legiscanType: text('legiscan_type'),
    legiscanDocId: integer('legiscan_doc_id'),
    legiscanTextHash: text('legiscan_text_hash'),
    document: jsonb('document'),
    sourceUrlXml: text('source_url_xml'),
    sourceUrlPdf: text('source_url_pdf'),
    sourceUrlHtm: text('source_url_htm'),
    sourceHash: text('source_hash'),
    fetchedAt: timestamp('fetched_at', { withTimezone: true }),
    parser: text('parser'),
    parserVersion: text('parser_version'),
    status: text('status').notNull().default('pending'),
    error: text('error'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.billKey, t.versionCode] })],
);

export const amendments = pgTable('amendments', {
  amendmentId: text('amendment_id').primaryKey(),
  billKey: text('bill_key').notNull(),
  baseVersionCode: text('base_version_code').notNull(),
  chamber: text('chamber'),
  sponsor: text('sponsor'),
  kind: text('kind'),
  scope: text('scope'),
  adopted: boolean('adopted').notNull().default(false),
  floorAction: text('floor_action'),
  actionDate: date('action_date'),
  legiscanAmendmentId: integer('legiscan_amendment_id'),
  legiscanHash: text('legiscan_hash'),
  document: jsonb('document'),
  sourceUrlXml: text('source_url_xml'),
  sourceUrlPdf: text('source_url_pdf'),
  sourceHash: text('source_hash'),
  fetchedAt: timestamp('fetched_at', { withTimezone: true }),
  status: text('status').notNull().default('pending'),
  error: text('error'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const hearings = pgTable('hearings', {
  id: text('id').primaryKey(),
  billKey: text('bill_key').notNull(),
  committee: text('committee').notNull(),
  chamber: text('chamber'),
  hearingAt: timestamp('hearing_at', { withTimezone: true }).notNull(),
  kind: text('kind').notNull(),
  source: text('source').notNull().default('legiscan'),
  description: text('description'),
  location: text('location'),
  cancelled: boolean('cancelled').notNull().default(false),
  revisedAt: timestamp('revised_at', { withTimezone: true }).notNull().defaultNow(),
});

export const priorFiscalNotes = pgTable('prior_fiscal_notes', {
  id: text('id').primaryKey(),
  billKey: text('bill_key').notNull(),
  packageId: integer('package_id'),
  label: text('label').notNull(),
  versionLabel: text('version_label'),
  kind: text('kind'),
  amendmentName: text('amendment_name'),
  url: text('url').notNull(),
  publishedAt: date('published_at'),
  legiscanSupplementId: integer('legiscan_supplement_id'),
});

export const ingestRuns = pgTable('ingest_runs', {
  id: uuid('id').primaryKey(),
  source: text('source').notNull(),
  path: text('path'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  status: text('status').notNull().default('running'),
  stats: jsonb('stats').notNull().default({}),
  error: text('error'),
  requestedBy: text('requested_by'),
});
