// Generates THIRD_PARTY.md from the installed production dependencies of the shipped apps and packages,
// and fails when a component carries a license outside the permitted set (MIT, BSD, Apache, MPL, ISC, 0BSD, Unlicense, CC0).
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ALLOWED = /^(MIT|BSD-[23]-Clause|BSD-3-Clause-Clear|Apache-2\.0|MPL-2\.0|ISC|0BSD|Unlicense|CC0-1\.0|BlueOak-1\.0\.0|Python-2\.0|CC-BY-4\.0|CC-BY-3\.0|Zlib|W3C|LGPL-3\.0-or-later|LGPL-2\.1-or-later)$/;
const SHIPPED = ['apps/api', 'apps/web', 'packages/billref', 'packages/bill-document', 'packages/note-schema', 'packages/workflow-machine', 'packages/api-client'];

const seen = new Map();
const problems = [];

function licenseOf(pkg) {
  if (typeof pkg.license === 'string') return pkg.license;
  if (pkg.license?.type) return pkg.license.type;
  if (Array.isArray(pkg.licenses)) return pkg.licenses.map((l) => l.type ?? l).join(' OR ');
  return 'UNKNOWN';
}

function allowed(expr) {
  return expr
    .replace(/[()]/g, '')
    .split(/\s+(?:OR|AND)\s+/i)
    .some((part) => ALLOWED.test(part.trim()));
}

function findPackageDir(dep, fromDir, require) {
  try {
    return dirname(require.resolve(`${dep}/package.json`));
  } catch { /* package.json not exported */ }
  try {
    let d = dirname(require.resolve(dep));
    for (let i = 0; i < 8 && d !== dirname(d); i++) {
      const pj = join(d, 'package.json');
      if (existsSync(pj) && JSON.parse(readFileSync(pj, 'utf8')).name === dep) return d;
      d = dirname(d);
    }
  } catch { /* no main entry */ }
  const candidates = [
    join(fromDir, 'node_modules', dep),
    join(dirname(fromDir), dep),
    join(root, 'node_modules', dep),
    join(root, 'node_modules', '.pnpm', 'node_modules', dep),
  ];
  return candidates.find((c) => existsSync(join(c, 'package.json')));
}

function walk(dir, stack = new Set()) {
  const pkgPath = join(dir, 'package.json');
  if (!existsSync(pkgPath)) return;
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const require = createRequire(pkgPath);
  for (const dep of Object.keys(pkg.dependencies ?? {})) {
    if (dep.startsWith('@wa-leg/')) {
      const local = SHIPPED.map((s) => join(root, s)).find((p) => existsSync(join(p, 'package.json')) && JSON.parse(readFileSync(join(p, 'package.json'), 'utf8')).name === dep);
      if (local && !stack.has(local)) walk(local, new Set([...stack, local]));
      continue;
    }
    const depDir = findPackageDir(dep, dir, require);
    if (!depDir) {
      problems.push(`${dep}: not resolvable from ${dir}`);
      continue;
    }
    const depPkg = JSON.parse(readFileSync(join(depDir, 'package.json'), 'utf8'));
    const key = `${depPkg.name}@${depPkg.version}`;
    if (seen.has(key)) continue;
    const lic = licenseOf(depPkg);
    seen.set(key, { name: depPkg.name, version: depPkg.version, license: lic, homepage: depPkg.homepage ?? depPkg.repository?.url ?? '' });
    if (!allowed(lic)) problems.push(`${key}: license ${lic} is not in the permitted set`);
    if (!stack.has(depDir)) walk(depDir, new Set([...stack, depDir]));
  }
}

for (const s of SHIPPED) {
  const dir = join(root, s);
  if (existsSync(dir)) walk(dir, new Set([dir]));
}

const rows = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
const lines = ['# Third-party components', '', 'Production dependencies of the shipped bundle, generated by `pnpm third-party`.', '', '| Package | Version | License |', '|---|---|---|'];
for (const r of rows) lines.push(`| ${r.homepage ? `[${r.name}](${r.homepage.replace(/^git\+/, '').replace(/\.git$/, '')})` : r.name} | ${r.version} | ${r.license} |`);
lines.push('');
writeFileSync(join(root, 'THIRD_PARTY.md'), lines.join('\n'));
console.log(`THIRD_PARTY.md: ${rows.length} components`);
if (problems.length) {
  console.error(problems.join('\n'));
  process.exit(1);
}
