/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            userId: string;
                            displayName: string;
                            email?: string;
                            roles: ("drafter" | "reviewer" | "viewer" | "admin")[];
                            /** @default [] */
                            divisions: string[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Known users (for assignment pickers), optionally filtered by role */
        get: {
            parameters: {
                query?: {
                    role?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            userId: string;
                            displayName: string;
                            email: string | null;
                            roles: string[];
                            divisions: string[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OIDC login (redirect) */
        get: {
            parameters: {
                query?: {
                    returnTo?: string;
                    login_hint?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC callback */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** End session and redirect to the app */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** End session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            version: string;
                            commit: string;
                            checks: {
                                [key: string]: {
                                    ok: boolean;
                                    detail?: string;
                                };
                            };
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            version: string;
                            commit: string;
                            checks: {
                                [key: string]: {
                                    ok: boolean;
                                    detail?: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log query */
        get: {
            parameters: {
                query?: {
                    objectType?: string;
                    objectId?: string;
                    actor?: string;
                    action?: string;
                    from?: string;
                    to?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            actorId: string;
                            action: string;
                            objectType: string;
                            objectId: string;
                            before: unknown | null;
                            after: unknown | null;
                            requestId: string | null;
                            at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse a bill reference and resolve it to a bill and version */
        get: {
            parameters: {
                query: {
                    ref: string;
                    biennium?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bills (paged) */
        get: {
            parameters: {
                query?: {
                    biennium?: string;
                    q?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            billKey: string;
                            id: string;
                            biennium: string;
                            title: string;
                            status: string | null;
                            currentVersionCode: string | null;
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill summary with version list, hearings, prior fiscal notes, companion */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            billKey: string;
                            biennium: string;
                            id: string;
                            type: string;
                            number: number;
                            chamber: string;
                            title: string;
                            description?: string;
                            status?: string;
                            statusDate?: string;
                            sponsors: unknown[];
                            committee?: unknown;
                            currentVersionCode: string;
                            versions: {
                                code: string;
                                label: string;
                                shortLabel: string;
                                seq: number;
                                status: string;
                                date?: string;
                                amendmentIds: string[];
                                sourceUrls: {
                                    xml?: string;
                                    pdf?: string;
                                    htm?: string;
                                };
                            }[];
                            hearings: {
                                id: string;
                                billKey: string;
                                versionCode?: string;
                                committee: string;
                                chamber?: string;
                                kind: string;
                                hearingAt: string;
                                location?: string;
                                description?: string;
                                cancelled: boolean;
                                hasNote?: boolean;
                            }[];
                            priorFiscalNotes: {
                                id: string;
                                packageId?: number;
                                label: string;
                                versionLabel?: string;
                                kind?: string;
                                url: string;
                                publishedAt?: string;
                            }[];
                            companion?: {
                                billKey: string;
                                id: string;
                                title?: string;
                            } | null;
                            rcwAffected: unknown[];
                            history: unknown[];
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/versions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill Document for one version (code=current resolves to the newest) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bill Document (packages/bill-document/schemas/bill-document.json) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            schemaVersion: string;
                            bill: {
                                [key: string]: unknown;
                            };
                            version: {
                                [key: string]: unknown;
                            };
                            header: {
                                [key: string]: unknown;
                            };
                            sections: {
                                [key: string]: unknown;
                            }[];
                            provenance: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/versions/{code}/sections/{sectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One section of a version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                    code: string;
                    sectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version-to-version diff (to may be amend:{amendmentId} for a striking amendment) */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                    mode?: "as-printed" | "effect";
                };
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VersionDiff (design/research/bill-viewer.md section 5) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            bill: {
                                [key: string]: unknown;
                            };
                            from: string;
                            to: string;
                            mode: string;
                            sections: {
                                [key: string]: unknown;
                            }[];
                            summary: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/amendments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Amendments of a bill */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            amendmentId: string;
                            kind: string;
                            scope?: string;
                            chamber?: string;
                            sponsor?: string;
                            baseVersionCode: string;
                            adopted: boolean;
                            floorAction?: string;
                            date?: string;
                            status: string;
                            effect?: string;
                            drafterCode?: string;
                            floorNumber?: string;
                            pdfUrl?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/amendments/{amendmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Amendment Document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                    amendmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/hearings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hearings and executive sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            billKey: string;
                            versionCode?: string;
                            committee: string;
                            chamber?: string;
                            kind: string;
                            hearingAt: string;
                            location?: string;
                            description?: string;
                            cancelled: boolean;
                            hasNote?: boolean;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hearings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming hearings across bills inside a window (default: next 72 hours) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    biennium?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            billKey: string;
                            versionCode?: string;
                            committee: string;
                            chamber?: string;
                            kind: string;
                            hearingAt: string;
                            location?: string;
                            description?: string;
                            cancelled: boolean;
                            hasNote?: boolean;
                            biennium: string;
                            billId: string;
                            title: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest run history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Start an ingest run (legiscan dataset path or refresh) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default refresh
                         * @enum {string}
                         */
                        source?: "legiscan" | "refresh";
                        path?: string;
                        billKeys?: string[];
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            job_id: string;
                            status_url: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Text search with direct-hit resolution, filters, facets (research/search.md section 6.1) */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    biennium?: string;
                    chamber?: "H" | "S";
                    type?: string;
                    status?: string;
                    committee?: string;
                    sponsor?: string;
                    has_fiscal_note?: boolean | string;
                    fiscal_note_status?: string;
                    doc_type?: string;
                    rcw?: string;
                    version_code?: string;
                    date_from?: string;
                    date_to?: string;
                    assigned_to_me?: boolean | string;
                    page?: number;
                    size?: number;
                    sort?: "relevance" | "date" | "bill_number";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search-as-you-type suggestions */
        get: {
            parameters: {
                query: {
                    q: string;
                    biennium?: string;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild or refresh indices (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default incremental
                         * @enum {string}
                         */
                        scope?: "full" | "incremental" | "bill";
                        bill_keys?: string[];
                        indices?: string[];
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            job_id: string;
                            status_url: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates */
        get: {
            parameters: {
                query?: {
                    mode?: "limited" | "full";
                    kind?: "document" | "snippet";
                    taxType?: string;
                    impactType?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            kind: "document" | "snippet";
                            /** @enum {string} */
                            mode: "limited" | "full";
                            version: number;
                            description: string;
                            file?: string;
                            tags: string[];
                            parts: string[];
                            tables: string[];
                            slots: {
                                id: string;
                                required: boolean;
                                hint?: string;
                            }[];
                            tokens: string[];
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template with HTML body */
        get: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            kind: "document" | "snippet";
                            /** @enum {string} */
                            mode: "limited" | "full";
                            version: number;
                            description: string;
                            file?: string;
                            tags: string[];
                            parts: string[];
                            tables: string[];
                            slots: {
                                id: string;
                                required: boolean;
                                hint?: string;
                            }[];
                            tokens: string[];
                            updatedAt: string;
                            html: string;
                            etag: string;
                        };
                    };
                };
            };
        };
        /** Update a template (admin); creates a new template version */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string;
                        html?: string;
                        tags?: string[];
                        /** @enum {string} */
                        kind?: "document" | "snippet";
                        /** @enum {string} */
                        mode?: "limited" | "full";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            kind: "document" | "snippet";
                            /** @enum {string} */
                            mode: "limited" | "full";
                            version: number;
                            description: string;
                            file?: string;
                            tags: string[];
                            parts: string[];
                            tables: string[];
                            slots: {
                                id: string;
                                required: boolean;
                                hint?: string;
                            }[];
                            tokens: string[];
                            updatedAt: string;
                            html: string;
                            etag: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template rendered with a note's token context */
        get: {
            parameters: {
                query?: {
                    noteId?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference/template-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Base template token context for the session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference/{set}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference data set (fiscal-years, accounts, revenue-sources, job-classes, phrases, wac-458) */
        get: {
            parameters: {
                query?: {
                    session?: string;
                };
                header?: never;
                path: {
                    set: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Note revisions visible to the caller */
        get: {
            parameters: {
                query?: {
                    billKey?: string;
                    state?: string;
                    assignee?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            noteRevisionId: string;
                            noteId: string;
                            billKey: string;
                            biennium: string;
                            billId: string;
                            billTitle?: string;
                            versionCode: string;
                            versionLabel: string;
                            /** @enum {string} */
                            state: "draft" | "in_review" | "changes_requested" | "approved" | "published";
                            drafter: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            reviewer: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            headVersion: number;
                            approvedVersion: number | null;
                            publishedAt: string | null;
                            publishedBy: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            publishedVersion: number | null;
                            templateId: string | null;
                            templateVersion: number | null;
                            /** @enum {string} */
                            mode: "limited" | "full";
                            editable: boolean;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a note in draft for a bill version from a template. Reviewers name the drafter; a drafter creates for themselves. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        billKey: string;
                        versionCode: string;
                        templateId: string;
                        drafterId?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            noteRevisionId: string;
                            noteId: string;
                            billKey: string;
                            biennium: string;
                            billId: string;
                            billTitle?: string;
                            versionCode: string;
                            versionLabel: string;
                            /** @enum {string} */
                            state: "draft" | "in_review" | "changes_requested" | "approved" | "published";
                            drafter: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            reviewer: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            headVersion: number;
                            approvedVersion: number | null;
                            publishedAt: string | null;
                            publishedBy: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            publishedVersion: number | null;
                            templateId: string | null;
                            templateVersion: number | null;
                            /** @enum {string} */
                            mode: "limited" | "full";
                            editable: boolean;
                            createdAt: string;
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{biennium}/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Note revisions on this bill visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    biennium: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            noteRevisionId: string;
                            noteId: string;
                            billKey: string;
                            biennium: string;
                            billId: string;
                            billTitle?: string;
                            versionCode: string;
                            versionLabel: string;
                            /** @enum {string} */
                            state: "draft" | "in_review" | "changes_requested" | "approved" | "published";
                            drafter: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            reviewer: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            headVersion: number;
                            approvedVersion: number | null;
                            publishedAt: string | null;
                            publishedBy: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            publishedVersion: number | null;
                            templateId: string | null;
                            templateVersion: number | null;
                            /** @enum {string} */
                            mode: "limited" | "full";
                            editable: boolean;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Note revision summary (bill, version, state, drafter, reviewer, publication) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            noteRevisionId: string;
                            noteId: string;
                            billKey: string;
                            biennium: string;
                            billId: string;
                            billTitle?: string;
                            versionCode: string;
                            versionLabel: string;
                            /** @enum {string} */
                            state: "draft" | "in_review" | "changes_requested" | "approved" | "published";
                            drafter: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            reviewer: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            headVersion: number;
                            approvedVersion: number | null;
                            publishedAt: string | null;
                            publishedBy: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            publishedVersion: number | null;
                            templateId: string | null;
                            templateVersion: number | null;
                            /** @enum {string} */
                            mode: "limited" | "full";
                            editable: boolean;
                            createdAt: string;
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Save head document (autosave). Requires If-Match with the current version. */
        put: {
            parameters: {
                query?: {
                    force?: boolean | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        doc: {
                            [key: string]: unknown;
                        };
                        /** @enum {string} */
                        mode: "limited" | "full";
                        clientId?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document versions (autosave heads and named snapshots) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Name a snapshot of the head */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        label?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/versions/{v}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A stored document version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    v: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/versions/{v}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a version as the new head */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    v: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redline between two document versions plus a table-cell diff */
        get: {
            parameters: {
                query: {
                    from: number;
                    to: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the head document (required slots, table reconciliation) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comment threads */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Open a thread anchored to a range */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        anchorText: string;
                        body: string;
                        id?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/comments/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a thread (author or reviewer) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Resolve or reopen a thread */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "open" | "resolved";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/notes/{id}/comments/{cid}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply in a thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        body: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export (link form: opens in the browser) */
        get: {
            parameters: {
                query: {
                    format: "html" | "pdf" | "docx" | "xml";
                    version?: number;
                    comments?: boolean | string;
                    strict?: boolean | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Export a document version as docx, pdf, xml (FNS placeholder), or html */
        post: {
            parameters: {
                query: {
                    format: "html" | "pdf" | "docx" | "xml";
                    version?: number;
                    comments?: boolean | string;
                    strict?: boolean | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stored exports of this revision */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a stored export */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    exportId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export job status (exports run synchronously; the job is the stored export) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit rows for this note revision */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow state, drafter, reviewer, events available to the caller, open change request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            instanceId: string;
                            noteRevisionId: string;
                            /** @enum {string} */
                            state: "draft" | "in_review" | "changes_requested" | "approved" | "published";
                            version: number;
                            drafter: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            reviewer: {
                                userId: string;
                                displayName?: string;
                            } | null;
                            availableEvents: {
                                /** @enum {string} */
                                type: "SUBMIT" | "REQUEST_CHANGES" | "APPROVE" | "PUBLISH";
                                label: string;
                            }[];
                            changeRequest: {
                                message: string;
                                by: {
                                    userId: string;
                                    displayName?: string;
                                };
                                at: string;
                            } | null;
                            editable: boolean;
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Send an event: SUBMIT, REQUEST_CHANGES (message required), APPROVE, PUBLISH */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        event: "SUBMIT" | "REQUEST_CHANGES" | "APPROVE" | "PUBLISH";
                        message?: string;
                        expectedVersion?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            instanceId: string;
                            state: string;
                            version: number;
                            seq: number;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition history (newest first) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    before?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
